const actionTypes = {
  FETCH_PRODUCT_REQUEST: "FETCH_PRODUCT_REQUEST",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILURE: "FETCH_PRODUCT_FAILURE",
  UPDATE_PRODUCT_DETAILS: "UPDATE_PRODUCT_DETAILS",
  FETCH_CATEGORY_REQUEST: "FETCH_CATEGORY_REQUEST",
  FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
  FETCH_CATEGORY_FAILURE: "FETCH_CATEGORY_FAILURE",
  UPDATE_CATEGORY_DETAILS: "UPDATE_CATEGORY_DETAILS",
};
export default actionTypes;
